### PR TITLE
Including kiwi/stoat classification activity

### PR DESCRIPTION
**Pull request by victor-wildlife**
Hi Dale,
I have included the sb3 template and worksheets (pdf and word) for an activity where students recognise images of kiwi birds and stoats.

The worksheet is in [this google doc](https://drive.google.com/file/d/1rwefNkh-cnjN4NbOn4SAPsQJ6aq_E9qZ/view?usp=sharing), please request access to it if you want to change/edit something.

Cheers,
Victor

### CODE REVIEW

**Comment by dalelane** [comment]
@victor-wildlife This looks great, thanks! 

The link to https://wildlife.ai/portfolio-items/kiwi-and-stoat-photos isn't working for me - is it not live yet?

**Comment by victor-wildlife** [comment]
Hi Dale,

I am updating our website this week. Currently, the training photos are in [https://www.screenbrands.com/portfolio-items/kiwi-and-stoat-photos/](https://www.screenbrands.com/portfolio-items/kiwi-and-stoat-photos/). 

I will let you know when the link I've included in the worksheet is live. Meanwhile, please let me know if there are any edits for the worksheet.

**Comment by dalelane** [comment]
My only suggestion for the worksheet is that you may want to include some credit that you wrote it - perhaps as a footer, and/or something on the front-page. Otherwise it looks fine to me. Thanks, again!

**Comment by victor-wildlife** [comment]
Hello Dale,
The link [https://wildlife.ai/portfolio-items/kiwi-and-stoat-photos](https://wildlife.ai/portfolio-items/kiwi-and-stoat-photos) is now live. I am happy to upload the [latest version of the worksheet](https://drive.google.com/file/d/1rwefNkh-cnjN4NbOn4SAPsQJ6aq_E9qZ/view?usp=sharing) here again if you are happy with it.

Cheers,
Victor

**Comment by dalelane** [comment]
Yes, please do - that's looking great. 

_(Sorry for the delay in replying - I've been super busy in the last week!)_

**Comment by victor-wildlife** [comment]
I just uploaded the updated versions of the worksheets

**Review by dalelane — APPROVED** [review]

**Comment by dalelane** [comment]
This is fantastic - thank you!

**Pull request merged**
